name: build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: fiam/arm-none-eabi-gcc@v1.0.2

      - name: Build
        run : |
          mkdir build
          cd build
          cmake -DCMAKE_TOOLCHAIN_FILE=../CMake/arm-none-eabi-gcc.cmake ..
          make
